variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/repository
  key: "$CI_BUILD_REF_NAME"

stages:
  - prepare
  - test
  - build
  - deploy

prepare_job:
  stage: prepare
  script:
    - java --version
    - mvn --version
    - ls -a

test-job:
  stage: test
  script:
    - mvn test

build-job:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - mvn clean compile jib:build

deploy-job:
  stage: deploy
  before_script:
    - docker logout
  script:
    - docker-compose up -d