variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/repository
  key: "$CI_BUILD_REF_NAME"

.docker-login-script:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - prepare
  - test
  - build
  - stage-deploy
  - prod-deploy

prepare_job:
  stage: prepare
  script:
    - java --version
    - mvn --version

test-job:
  stage: test
  script:
    - mvn test

build-job:
  stage: build
  before_script:
    - !reference [.docker-login-script, script]
  script: 
    - mvn clean compile jib:build

stage-deploy-job:
  stage: stage-deploy
  before_script:
    - !reference [.docker-login-script, script]
  script:
    - docker-compose -f docker-compose-stage.yaml pull
    - docker-compose -f docker-compose-stage.yaml up -d

prod-deploy-job:
  stage: prod-deploy
  before_script:
    - !reference [.docker-login-script, script]
  script:
    - scp -o StrictHostKeyChecking=no docker-compose-prod.yaml lazarev@10.168.1.5:/home/lazarev/docker-compose-prod.yaml
    - ssh -o StrictHostKeyChecking=no lazarev@10.168.1.5 "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker-compose -f docker-compose-prod.yaml pull &&
        docker-compose -f docker-compose-prod.yaml up -d"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'