version: "3.3"
services:
  app:
    image: registry.gitlab.com/utc873508/logistic-param-service:1.3
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - sql:/app/sql
      - button:/app/button
      - logging:/app/logging
    environment:
      TZ: "Europe/Moscow"