version: "3.3"
services:
  app:
    image: registry.gitlab.com/utc873508/logistic-param-service:1.3
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./sql:/sql
      - ./button:/button
      - /home/m.lazarev/workdir/logging:/logging
      - /data:/data
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      TZ: "Europe/Moscow"