version: "3.3"
services:
  app:
    image: registry.gitlab.com/utc873508/logistic-param-service:1.3
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./sql:/sql
      - ./button:/button
      - ./logging:/logging
    environment:
      TZ: "Europe/Moscow"