spring:
  datasource:
    itr:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=ITR;trustServerCertificate=true
      username:
      password:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    utcsrs:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=Utc_srs;trustServerCertificate=true
      username:
      password:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    integration-data:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=IntegrationData;trustServerCertificate=true
      username:
      password:
    postgres:
      jdbc-url: jdbc:postgresql://10.168.1.6:5432/params
      username:
      password: 
      driverClassname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

  profiles:
    active: 'dev'

params:
  nextDataLoadTimeCron: '0 0 4 * * *'
  nextFlightRequirementLoadTimeCron: '0 30 4 * * *'