spring:
  datasource:
    itr:
      jdbc-url: jdbc:sqlserver://10.168.0.8:1433;database=ITR;trustServerCertificate=true
      username: Obmen
      password: 321654987
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    utcsrs:
      jdbc-url: jdbc:sqlserver://10.168.0.8:1433;database=Utc_srs;trustServerCertificate=true
      username: Obmen
      password: 321654987
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    integration-data:
      jdbc-url: jdbc:sqlserver://10.168.0.8:1433;database=IntegrationData;trustServerCertificate=true
      username: Obmen
      password: 321654987
    postgres:
      jdbc-url: jdbc:postgresql://10.168.1.6:5432/log_param
      username: admin
      password: 123456
      driverClassname: org.postgresql.Driver
    rjd:
      jdbc-url: jdbc:postgresql://10.168.1.6:5432/rjd
      username: admin
      password: 123456
      driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

application:
  address: 'http://10.168.1.6:8080'
