spring:
  datasource:
    itr:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=ITR;trustServerCertificate=true
      username:
      password:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    utcsrs:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=Utc_srs;trustServerCertificate=true
      username:
      password:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    postgres:
      jdbc-url: jdbc:postgresql://10.168.1.6:5432/log_param
      username:
      password: 
      driverClassname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

  profiles:
    active: "dev"

params:
  daysToRetrieveData: 90
  nextDataLoadTime: '05:00:00'
  maxLoadIdleDays: 20
  maxUnloadIdleDays: 20
  minLoadIdleDays: 0
  minUnloadIdleDays: 0
  maxTravelTime: 60
  minTravelTime: 1
  nextDataLoadTimeCron: '0 0 4 * * *'
  flightProfitDaysToRetrieveData: 45