spring:
  datasource:
    itr:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=ITR;trustServerCertificate=true
      username: Obmen
      password: 321654987
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    utcsrs:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=Utc_srs;trustServerCertificate=true
      username: Obmen
      password: 321654987
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    integration-data:
      jdbc-url: jdbc:sqlserver://dbsrv:1433;database=IntegrationData;trustServerCertificate=true
      username: Obmen
      password: 321654987
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/flight_db
      username: postgres
      password: root
      driverClassname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false

  profiles:
    active: 'dev'